import type { Metadata } from "next";
import "./globals.css";
import ClientLayout from "./ClientLayout";
import SessionProviderWrapper from "./SessionProviderWrapper";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import ReactQueryProvider from "./ReactQueryProvider";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <SessionProviderWrapper>
            <ClientLayout>{children}</ClientLayout>
          </SessionProviderWrapper>
        </ReactQueryProvider>
        <Toaster position="top-right" reverseOrder={false} />
      </body>
    </html>
  );
}
